
//normally we get the Person model after it is generated by the backend
//for the perposes of this assignement it will be written manually

interface Person {
    id?: number;
    firstName?: string;
    lastName?: string;
}

export default Person;